# Use a slim Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY . .

# Expose ports (optional, for documentation)
EXPOSE 8000
EXPOSE 8001

# Commands after this will be run by the docker-compose.yml file
